### ISSUE TITLE
Update showing even local version is greater

### ISSUE THREAD

**Issue by faisalmushtaq007** [timtraversy/new_version#64] opened 2021-09-30 07:24 UTC
I'm getting this:\
[log] First beta release of the application for open testing.
[log] https://play.google.com/store/apps/details?id=com.rationaltabs.meir_shop
[log] 1.0.2 (localversion)
[log] Varies with device (storevesion)
[log] true

i am using latest version of package

**Comment by timtraversy** [comment] 2021-09-30 13:43
Thanks, closing as duplicate of #54

**Closed** 2021-09-30 13:43 UTC
