### ISSUE TITLE
Value invalid range error

### ISSUE THREAD

**Issue by asad561** [timtraversy/new_version#55] opened 2021-08-11 11:58 UTC
<asynchronous suspension>
2021-08-11 16:39:25.576776+0500 Runner[6227:4820110] flutter: connected
2021-08-11 16:39:26.751187+0500 Runner[6227:4820110] [VERBOSE-2:ui_dart_state.cc(213)] Unhandled Exception: RangeError (index): Invalid value: Valid value range is empty: 0
#0      List.[] (dart:core-patch/growable_array.dart:254:60)
#1      NewVersion._getiOSStoreVersion (package:new_version/new_version.dart:127:39)
<asynchronous suspension>

My bundle Id is **com.healthSolutions.healthService.iOS**.
I am struck at this for last 3 days where I am giving the correct bundle Id.

  || --- Attaching Screenshot --- ||

![Screenshot 2021-08-11 at 4 56 20 PM](https://user-images.githubusercontent.com/68374909/129024645-90762e7e-24cc-4f05-8c44-85ccc6bde20f.png)

**Comment by cirediew** [comment] 2021-08-20 11:16
Same for me
```
flutter: RangeError (index): Invalid value: Valid value range is empty: 0
flutter: 
#0      List.[] (dart:core-patch/growable_array.dart:254:60)
#1      NewVersion._getiOSStoreVersion (package:new_version/new_version.dart:127:39)
<asynchronous suspension>
#2      NewVersion.showAlertIfNecessary (package:new_version/new_version.dart:89:42)
<asynchronous suspension>
```
When calling this code, just like the example project.
```dart
final newVersion = NewVersion();
newVersion.showAlertIfNecessary(context: context);
```

**Comment by asad561** [comment] 2021-08-23 05:37
> Same for me
> 
> ```
> flutter: RangeError (index): Invalid value: Valid value range is empty: 0
> flutter: 
> #0      List.[] (dart:core-patch/growable_array.dart:254:60)
> #1      NewVersion._getiOSStoreVersion (package:new_version/new_version.dart:127:39)
> <asynchronous suspension>
> #2      NewVersion.showAlertIfNecessary (package:new_version/new_version.dart:89:42)
> <asynchronous suspension>
> ```
> 
> When calling this code, just like the example project.
> 
> ```dart
> final newVersion = NewVersion();
> newVersion.showAlertIfNecessary(context: context);
> ```

I Just remove this plugin and do it manually very easily, I set a new version number in API and then check if a local version of the app and a new version of API is not matching show popup to update the application.

**Comment by timtraversy** [comment] 2021-08-24 15:52
Duplicate of #50

**Closed by timtraversy** 2021-08-24 15:52 UTC
