### ISSUE TITLE
No element Issue

### ISSUE THREAD

**Issue by RealYoungk** [timtraversy/new_version#80] opened 2021-12-20 03:21 UTC
I tried to use the new_version package, but the following error occurred.

@override
  void initState() {
    final newVersion = NewVersion(
        androidId: 'com.projectwith.withapp_did', iOSId: 'com.projectwith.withappDid', iOSAppStoreCountry: 'KR');
    newVersion.showAlertIfNecessary(context: context);
    super.initState();
  }

![image](https://user-images.githubusercontent.com/44742847/146705853-c2933f40-81de-45fa-8f50-9af0f47bca53.png)
![image](https://user-images.githubusercontent.com/44742847/146706988-0be0ceab-f9e8-43c6-81c1-aa3c27221848.png)
![image](https://user-images.githubusercontent.com/44742847/146707013-a2ac4392-66b5-4694-aafd-86e158804354.png)

How to edit this?

**Comment by timtraversy** [comment] 2021-12-20 22:53
Closing as duplicate of #74

**Closed** 2021-12-20 22:54 UTC
