### ISSUE TITLE
The argument type 'VersionStatus?' can't be assigned to the parameter type 'VersionStatus'

### ISSUE THREAD

**Issue by mius0070** [timtraversy/new_version#56] opened 2021-08-17 19:45 UTC
final status = await newVersion.getVersionStatus();
newVersion.showUpdateDialog(
      context: context,
      versionStatus: status, // The argument type 'VersionStatus?' can't be assigned to the parameter type 'VersionStatus' ,

    );

**Comment by chrisparton1991** [comment] 2021-08-17 23:28
Hi @mius0070, looking at the library code, a `null` version status will be returned if the version lookup was unsuccessful.

I think the safest thing to do in the case of an error would be to assume no new version, and log a warning somewhere if possible (e.g. to Crashlytics if you're using that).

So you'd have something like:
```
final status = await newVersion.getVersionStatus();

if (status == null) {
  logToSomewhere('Failed to retrieve app version status for ${Platform.operatingSystem}')
} else {
  newVersion.showUpdateDialog(
    context: context,
    versionStatus: status,
  );
}
```

**Comment by timtraversy** [comment] 2021-08-18 12:44
Thanks @chrisparton1991. Yes, this is a duplicate of #47. You can see more information there.

**Closed by timtraversy** 2021-08-18 12:44 UTC
